apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-app
  template:
    metadata:
      labels:
        app: github-app
    spec:
      containers:
      - name: github-app
        image: githubappworkflowswebapi:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            name: web
          - containerPort: 443
            name: web-secure
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: ASPNETCORE_URLS
            value: "https://+:443;http://+:80"
          - name: ASPNETCORE_Kestrel__Certificates__Default__Path
            value: "/root/.aspnet/https/GitHub.App.Workflows.WebApi.pfx"
          - name: ASPNETCORE_Kestrel__Certificates__Default__Password
            value: "88809a6d-5c36-42bd-9aeb-862f2e02d235"

---
apiVersion: v1
kind: Service
metadata:
  name: github-app-service
spec:
  type: NodePort
  selector:
    app: github-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http
    - port: 443
      targetPort: 443
      nodePort: 30443
      name: https
